print("startup")
gui.disable_logical_size()
--gui.set_logical_size(1280,720)
print(i18n_fmt("类型: {}","Test"))
print("╭◜◝ ͡ ◜ ╮ ")
print("( 诶！  ) ")
print("╰◟ ͜ ╭◜◝ ͡ ◜ ͡ ◝  ╮")
print("    (  云朵!    )")
print("╭◜◝ ͡ ◜◝ ͡  ◜ ╮◞ ╯")
print("( 哒哒哒哒哒  ) ")
print("╰◟ ͜ ◞ ͜ ◟ ͜ ◞◞╯ ╭◜◝ ͡ ◜ ͡ ◝ ◝  ͡ ◜╮")
print("              (   好想玩原神   )")
print("╭◜◝ ͡ ◜◝ ͡  ◜ ╮ ╰◟ ◞ ͜ ◟ ͜ ◞◞ ͜ ◟ ╯")
print("(    云原神！)  ")
print("╰◟ ͜ ◞ ͜ ◟ ͜ ◞◞╯")
print("₍ᐢ..ᐢ₎ᐝ")
snd.play_sfx("__Engine_SFX__@annc.mp3")
